sudo: false
language: go
script:
  - cd hystrix
  - go test -race -coverprofile=coverage.txt -covermode=atomic

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip

env:
  global:
    - GORACE="halt_on_error=1"

after_success:
  - bash <(curl -s https://codecov.io/bash)
